version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: poetry run python manage.py runserver 0.0.0.0:8000
    working_dir: /code/src/butler
    volumes:
      - .:/code
    environment:
      - "DJANGO_SECRET_KEY=nokey"
      - "DJANGO_DEBUG=True"
      - "DATABASE_URL=postgres://postgres:postgres@db/postgres"
      - "HOST=butler.local"
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data:
