# Generated by Django 4.2.1 on 2023-05-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("poster", models.CharField(max_length=100)),
                ("text", models.TextField()),
                ("inserted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-inserted_at",),
            },
        ),
    ]
